import type { Lang } from '@/lib/i18n/dictionaries';

export const COMMUNITY_EXPLORER_COPY = {
  en: {
    eyebrow: 'Communities',
    title: 'Explore communities',
    description:
      'Join open communities right away. Request access when approval is required. Public communities are marked as lower trust.',
    yourCommunities: 'Your communities',
    noMembershipsYet: 'No memberships yet',
    joinedCount: (count: number) => `${count} joined`,
    joinPrompt: 'Join a community below to start browsing and posting rides.',
    explore: 'Explore',
    availableCommunities: 'Available communities',
    inviteCode: 'Invite code',
    useDirectCode: 'Use a direct code',
    inviteDescription:
      'If you already have a code, we will join the community or submit a request automatically.',
    invitePlaceholder: 'Enter invite code',
    checking: 'Checking...',
    continue: 'Continue',
    joined: 'Joined',
    requestPending: 'Request pending',
    removing: 'Removing...',
    cancelRequest: 'Cancel request',
    requestDeclined: 'Request declined',
    adminNote: 'Admin note',
    updatedOn: 'Updated',
    sending: 'Sending...',
    requestAgain: 'Request again',
    joinCommunity: 'Join community',
    joining: 'Joining...',
    requestAccess: 'Request access',
    noCommunitiesYet: 'No communities are listed yet. If you have an invite code, use it below.',
    approvalRequired: 'Approval required',
    openToEveryone: 'Open to everyone',
    openJoin: 'Open join',
    lowerTrust: 'Lower trust community. Anyone can join.',
    verifiedTrust: 'Verified community membership.',
    roleMember: 'Member',
    roleAdmin: 'Admin',
    joinedNotice: (name: string) => `Joined ${name}.`,
    requestSentNotice: (name: string) => `Request sent to ${name}.`,
    requestRemovedNotice: (name: string) => `Request removed for ${name}.`,
    errors: {
      emptyInvite: 'Enter an invite code first.',
      communityNotFound: 'Community not found.',
      inviteCodeNotFound: 'Invite code not found.',
      unauthorized: 'You need to sign in again to continue.',
      requestExists: 'A join request is already pending for this community.',
      generic: 'Something went wrong. Please try again.',
    },
  },
  ar: {
    eyebrow: 'المجتمعات',
    title: 'استكشف المجتمعات',
    description:
      'انضم إلى المجتمعات المفتوحة مباشرة. اطلب الوصول عندما تكون الموافقة مطلوبة. يتم تمييز المجتمعات العامة بأنها أقل ثقة.',
    yourCommunities: 'مجتمعاتك',
    noMembershipsYet: 'لا توجد عضويات بعد',
    joinedCount: (count: number) => `تم الانضمام إلى ${count}`,
    joinPrompt: 'انضم إلى أحد المجتمعات أدناه لبدء تصفح الرحلات ونشرها.',
    explore: 'استكشاف',
    availableCommunities: 'المجتمعات المتاحة',
    inviteCode: 'رمز الدعوة',
    useDirectCode: 'استخدم رمزًا مباشرًا',
    inviteDescription:
      'إذا كان لديك رمز بالفعل، فسنضمك إلى المجتمع أو نرسل طلب الانضمام تلقائيًا.',
    invitePlaceholder: 'أدخل رمز الدعوة',
    checking: 'جارٍ التحقق...',
    continue: 'متابعة',
    joined: 'تم الانضمام',
    requestPending: 'الطلب قيد الانتظار',
    removing: 'جارٍ الإزالة...',
    cancelRequest: 'إلغاء الطلب',
    requestDeclined: 'تم رفض الطلب',
    adminNote: 'ملاحظة المشرف',
    updatedOn: 'تم التحديث',
    sending: 'جارٍ الإرسال...',
    requestAgain: 'إعادة الطلب',
    joinCommunity: 'الانضمام إلى المجتمع',
    joining: 'جارٍ الانضمام...',
    requestAccess: 'طلب الوصول',
    noCommunitiesYet: 'لا توجد مجتمعات معروضة بعد. إذا كان لديك رمز دعوة، فاستخدمه أدناه.',
    approvalRequired: 'تتطلب موافقة',
    openToEveryone: 'مفتوح للجميع',
    openJoin: 'انضمام مفتوح',
    lowerTrust: 'مجتمع أقل ثقة. يمكن لأي شخص الانضمام.',
    verifiedTrust: 'عضوية مجتمع موثقة.',
    roleMember: 'عضو',
    roleAdmin: 'مشرف',
    joinedNotice: (name: string) => `تم الانضمام إلى ${name}.`,
    requestSentNotice: (name: string) => `تم إرسال الطلب إلى ${name}.`,
    requestRemovedNotice: (name: string) => `تمت إزالة الطلب من ${name}.`,
    errors: {
      emptyInvite: 'أدخل رمز الدعوة أولاً.',
      communityNotFound: 'لم يتم العثور على المجتمع.',
      inviteCodeNotFound: 'لم يتم العثور على رمز الدعوة.',
      unauthorized: 'تحتاج إلى تسجيل الدخول مرة أخرى للمتابعة.',
      requestExists: 'يوجد طلب انضمام معلق بالفعل لهذا المجتمع.',
      generic: 'حدث خطأ ما. حاول مرة أخرى.',
    },
  },
  he: {
    eyebrow: 'קהילות',
    title: 'גלה קהילות',
    description:
      'הצטרף מיד לקהילות פתוחות. בקש גישה כשנדרש אישור. קהילות ציבוריות מסומנות כרמת אמון נמוכה יותר.',
    yourCommunities: 'הקהילות שלך',
    noMembershipsYet: 'עדיין אין חברות בקהילה',
    joinedCount: (count: number) => `${count} הצטרפויות`,
    joinPrompt: 'הצטרף לאחת הקהילות למטה כדי להתחיל לגלוש ולפרסם נסיעות.',
    explore: 'גילוי',
    availableCommunities: 'קהילות זמינות',
    inviteCode: 'קוד הזמנה',
    useDirectCode: 'השתמש בקוד ישיר',
    inviteDescription:
      'אם כבר יש לך קוד, נצרף אותך לקהילה או נשלח בקשת הצטרפות באופן אוטומטי.',
    invitePlaceholder: 'הזן קוד הזמנה',
    checking: 'בודק...',
    continue: 'המשך',
    joined: 'הצטרפת',
    requestPending: 'הבקשה ממתינה',
    removing: 'מסיר...',
    cancelRequest: 'בטל בקשה',
    requestDeclined: 'הבקשה נדחתה',
    adminNote: 'הערת מנהל',
    updatedOn: 'עודכן',
    sending: 'שולח...',
    requestAgain: 'בקש שוב',
    joinCommunity: 'הצטרף לקהילה',
    joining: 'מצטרף...',
    requestAccess: 'בקש גישה',
    noCommunitiesYet: 'עדיין אין קהילות מוצגות. אם יש לך קוד הזמנה, השתמש בו למטה.',
    approvalRequired: 'דורש אישור',
    openToEveryone: 'פתוח לכולם',
    openJoin: 'הצטרפות פתוחה',
    lowerTrust: 'קהילה ברמת אמון נמוכה יותר. כל אחד יכול להצטרף.',
    verifiedTrust: 'חברות בקהילה מאומתת.',
    roleMember: 'חבר',
    roleAdmin: 'מנהל',
    joinedNotice: (name: string) => `הצטרפת אל ${name}.`,
    requestSentNotice: (name: string) => `הבקשה נשלחה אל ${name}.`,
    requestRemovedNotice: (name: string) => `הבקשה הוסרה עבור ${name}.`,
    errors: {
      emptyInvite: 'יש להזין קודם קוד הזמנה.',
      communityNotFound: 'הקהילה לא נמצאה.',
      inviteCodeNotFound: 'קוד ההזמנה לא נמצא.',
      unauthorized: 'צריך להתחבר מחדש כדי להמשיך.',
      requestExists: 'כבר קיימת בקשת הצטרפות ממתינה לקהילה הזאת.',
      generic: 'משהו השתבש. נסה שוב.',
    },
  },
} satisfies Record<Lang, Record<string, unknown>>;

export function localizeCommunityExplorerError(message: string, lang: Lang) {
  const copy = COMMUNITY_EXPLORER_COPY[lang] ?? COMMUNITY_EXPLORER_COPY.en;
  const normalized = message.trim().toLowerCase();

  if (normalized.includes('community not found')) return copy.errors.communityNotFound;
  if (normalized.includes('invite code not found')) return copy.errors.inviteCodeNotFound;
  if (normalized.includes('unauthorized')) return copy.errors.unauthorized;
  if (normalized.includes('already pending')) return copy.errors.requestExists;
  if (normalized.includes('sign in')) return copy.errors.unauthorized;

  return lang === 'en' ? message : copy.errors.generic;
}
